# Generated by Django 3.0.8 on 2020-07-02 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='X is last position on the falling leaves')),
            ],
        ),
    ]
